version: "3.9"

services:
  collectivo-ux:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: yarn dev -- --host
    restart: always
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_KEYCLOAK_URL=http://keycloak:8080
    ports:
      - "5173:5173"

volumes:
  db-data:
  backend:
