name: Release tag
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build-collectivo-ux-docker-push:
    name: Release collectivo-ux to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          rename: '@jaywcjlove/github-action-package-test'
      - name: Build container image
        run: |
          docker build -t milawien/collectivo-ux:latest
          docker push milawien/collectivo-ux:latest